
const Path = {
  Home: "/",
  Register: "/register",
  Login: "/login",
  About: "/about",
  Blog: "/blog",
  Cart: "/cart",
  NotFound: '/404',
  Logout: '/logout',
  DogFood: '/dog-food',
  CatFood: '/cat-food',
  BlogDetails: '/details/:articleId',
  Service: '/services',
  Profile: '/profile',
  Contact: '/contact',
  DogCategory: '/dog-category',
  CatCategory: '/cat-category',
  Adoption: '/adoption',
  CreatePost: 'create-post',
  AdminPanel: '/admin',
  CreateArticle: '/create-article',
  Select: "/selection",
  CatToys: '/cat-toys',
  CatTreats: '/cat-treats',
  DogToys: '/dog-toys',
  DogTreats: '/dog-treats',
  CreatePost: '/profile/create-post',
  Orders: '/profile/orders',
  Order: '/profile/orders/order/:orderId',
  ProfileInfo: '/profile/information',
  Messages: '/profile/messages',
  CreateProduct: '/create-product',
  CreateCategory: '/create-category',
  ThankYou: '/thank-you',
  EditPost: '/edit-post/:id',
  EditArticle: '/edit-article/:id',
  EditProduct: '/edit-product/:id',
  PostDetails: '/adoption/:animalId',
  ArticleDetails: '/details/:articleId',
  ProductDetails: '/product/details/:productId',
};

export default Path;
